### PR TITLE
modified models to add additional parameters 

### PR DESCRIPTION
**Pull request by hussu010**

### CODE REVIEW

**Comment by Emibrown** [comment]
@dhakal0kushal  How do you intend to populate the ID field?

**Comment by hussu010** [comment]
ID will be the slug of the coin.. we'll populate the ID in the same way as to how we are going to get the name, description, website address and so on

**Comment by Emibrown** [comment]
what's the different between id and symbol

**Comment by hussu010** [comment]
ID will be used for us to identify a particular coin and the symbol is for showing the short form of the cryptocurrency. Example:
ID: bitcoin
name: Bitcoin
symbol: btc

**Pull request merged**
